### ISSUE TITLE
About NUCLE dataset

### ISSUE THREAD

**Issue by hejingcao** [gotutiyan/GEC-Info#3]
Recently I'd like to reproduce BART fine-tuning on GEC task (reference https://github.com/Katsumata420/generic-pretrained-GEC), but somehow I cannot connect the website [NUCLE (Release 3.3) Data](https://sterling8.d2.comp.nus.edu.sg/nucle_download/nucle.php). 

Is there any chance you share the NUCLE dataset with me? My mail is pkuchj2996@gmail.com. Thanks a lot!

**Comment by gotutiyan** [comment]
Hi @hejingcao 
It seems that the website certificate has expired about 4 days ago. I don't know whether or not NUS NLP team recognize this problem but it's better to wait more a few days.

To be honest, I don't understand about the license of distributing. I will avoid to send the data for now even in private sharing.

**Comment by hejingcao** [comment]
Yeah, it is the license problem. I will contact the NUS NLP group.
Thanks anyway for your apply.
